=== ErikFernandezConde/Kings-League/LMSG/UltimaJornada/ultimajornada.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="jornada" type="jornadaType"/>
  <xs:complexType name="PartidoType">
    <xs:sequence>
      <xs:element name="HORA" type="xs:string"/>
      <xs:element name="GOLES_EQ1" type="xs:string"/>
      <xs:element name="GOLES_EQ2" type="xs:string"/>
      <xs:element name="ID_Ganador" type="xs:string"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ID_PARTIDO" use="optional"/>
  </xs:complexType>
  <xs:complexType name="jornadaType">
    <xs:sequence>
      <xs:element type="xs:string" name="ID_JOR"/>
      <xs:element type="xs:string" name="ID_TEMP"/>
      <xs:element type="xs:string" name="Dia"/>
      <xs:element type="xs:string" name="TIPO"/>
      <xs:element type="PartidoType" name="Partido" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="NUMERO"/>
  </xs:complexType>
</xs:schema>

=== ErikFernandezConde/Kings-League/LMSG/UltimaJornada/ultimajornada.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jornada SYSTEM "ultimajornada.dtd">
<jornada NUMERO="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="ultimajornada.xsd">
    <ID_JOR>1</ID_JOR>
    <ID_TEMP>1</ID_TEMP>
    <Dia>01/01/2024</Dia>
    <TIPO>FaseRegular</TIPO>
       <Partido ID_PARTIDO="1">       
            <HORA>16:00</HORA>
            <GOLES_EQ1>3</GOLES_EQ1>
            <GOLES_EQ2>4</GOLES_EQ2>
            <ID_Ganador>5</ID_Ganador>
       </Partido> 
       
       <Partido ID_PARTIDO="2">       
            <HORA>17:00</HORA>
            <GOLES_EQ1>4</GOLES_EQ1>
            <GOLES_EQ2>2</GOLES_EQ2>
            <ID_Ganador>2</ID_Ganador>
       </Partido> 
       
       <Partido ID_PARTIDO="3">       
            <HORA>18:00</HORA>
            <GOLES_EQ1>3</GOLES_EQ1>
            <GOLES_EQ2>6</GOLES_EQ2>
            <ID_Ganador>10</ID_Ganador>
       </Partido> 
       
       <Partido ID_PARTIDO="4">       
            <HORA>19:00</HORA>
            <GOLES_EQ1>1</GOLES_EQ1>
            <GOLES_EQ2>5</GOLES_EQ2>
            <ID_Ganador>12</ID_Ganador>
       </Partido> 
       
       <Partido ID_PARTIDO="5">       
            <HORA>20:00</HORA>
            <GOLES_EQ1>5</GOLES_EQ1>
            <GOLES_EQ2>3</GOLES_EQ2>
            <ID_Ganador>7</ID_Ganador>
       </Partido> 
       
       <Partido ID_PARTIDO="6">       
            <HORA>21:00</HORA>
            <GOLES_EQ1>3</GOLES_EQ1>
            <GOLES_EQ2>5</GOLES_EQ2>
            <ID_Ganador>1</ID_Ganador>
       </Partido> 
  </jornada>
