=== ErikFernandezConde/Kings-League/LMSG/Clasificacion/clasificacion.dtd
<!ELEMENT Clasificaciones (Clasificacion)*>
        <!ELEMENT Clasificacion (POSICION|NOMBRE_EQUIPO|VICTORIAS|GOLES_A_FAVOR|GOLES_EN_CONTRA|DIFERENCIA_GOLES)*>
        <!ELEMENT POSICION (#PCDATA)>
        <!ELEMENT NOMBRE_EQUIPO (#PCDATA)>
        <!ELEMENT VICTORIAS (#PCDATA)>
        <!ELEMENT GOLES_A_FAVOR (#PCDATA)>
        <!ELEMENT GOLES_EN_CONTRA (#PCDATA)>
        <!ELEMENT DIFERENCIA_GOLES (#PCDATA)>

=== ErikFernandezConde/Kings-League/LMSG/Clasificacion/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clasificaciones SYSTEM "clasificacion.dtd">
<Clasificaciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="clasificacion.xsd">
 <Clasificacion>
  <POSICION>1</POSICION>
  <NOMBRE_EQUIPO>Jijantes FC</NOMBRE_EQUIPO>
  <VICTORIAS>8</VICTORIAS>
  <GOLES_A_FAVOR>32</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>32</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>0</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>2</POSICION>
  <NOMBRE_EQUIPO>Rayo Barcelona</NOMBRE_EQUIPO>
  <VICTORIAS>7</VICTORIAS>
  <GOLES_A_FAVOR>34</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>31</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>3</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>3</POSICION>
  <NOMBRE_EQUIPO>Porcinos FC</NOMBRE_EQUIPO>
  <VICTORIAS>7</VICTORIAS>
  <GOLES_A_FAVOR>37</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>30</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>7</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>4</POSICION>
  <NOMBRE_EQUIPO>Ultimate Móstoles</NOMBRE_EQUIPO>
  <VICTORIAS>6</VICTORIAS>
  <GOLES_A_FAVOR>27</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>29</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>-2</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>5</POSICION>
  <NOMBRE_EQUIPO>El Barrio</NOMBRE_EQUIPO>
  <VICTORIAS>5</VICTORIAS>
  <GOLES_A_FAVOR>24</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>34</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>-10</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>6</POSICION>
  <NOMBRE_EQUIPO>Saiyans FC</NOMBRE_EQUIPO>
  <VICTORIAS>5</VICTORIAS>
  <GOLES_A_FAVOR>29</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>33</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>-4</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>7</POSICION>
  <NOMBRE_EQUIPO>Pio</NOMBRE_EQUIPO>
  <VICTORIAS>5</VICTORIAS>
  <GOLES_A_FAVOR>29</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>31</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>-2</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>8</POSICION>
  <NOMBRE_EQUIPO>1K</NOMBRE_EQUIPO>
  <VICTORIAS>5</VICTORIAS>
  <GOLES_A_FAVOR>35</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>30</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>5</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>9</POSICION>
  <NOMBRE_EQUIPO>xBuyer Team</NOMBRE_EQUIPO>
  <VICTORIAS>5</VICTORIAS>
  <GOLES_A_FAVOR>33</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>29</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>4</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>10</POSICION>
  <NOMBRE_EQUIPO>Aniquiladores</NOMBRE_EQUIPO>
  <VICTORIAS>5</VICTORIAS>
  <GOLES_A_FAVOR>32</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>28</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>4</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>11</POSICION>
  <NOMBRE_EQUIPO>Kunisports</NOMBRE_EQUIPO>
  <VICTORIAS>4</VICTORIAS>
  <GOLES_A_FAVOR>31</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>30</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>1</DIFERENCIA_GOLES>
 </Clasificacion>
 <Clasificacion>
  <POSICION>12</POSICION>
  <NOMBRE_EQUIPO>Los Troncos FC</NOMBRE_EQUIPO>
  <VICTORIAS>4</VICTORIAS>
  <GOLES_A_FAVOR>23</GOLES_A_FAVOR>
  <GOLES_EN_CONTRA>29</GOLES_EN_CONTRA>
  <DIFERENCIA_GOLES>-6</DIFERENCIA_GOLES>
 </Clasificacion>
</Clasificaciones>
